title: "Cubicore: IoT Development Kit Documentation"
description: "Complete guide for Lorfi projects and applications"
baseurl: ""
url: "https://n0bh.github.io/cubikits.github.io/"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
header_pages:
  - docs/Software_Guide.html
  - docs/Hardware_Guide.html
  - docs/Components_Lists.html

# Collections for better organization
collections:
  projects:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"